# Generated by Django 3.0 on 2020-04-02 06:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Ui', 'Ui'), ('Rest Api', 'Rest Api'), ('Flask', 'Flask'), ('Mysql', 'Mysql')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('Narayana', 'Narayana'), ('Mahesh', 'Mahesh'), ('Mohan Reddy', 'Mohan Reddy'), ('Srinivas', 'Srinivas'), ('Wilson', 'Wilson')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyd'), ('Bang', 'Bang'), ('Pune', 'Pune'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning'), ('After Noon', 'After Noon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratting', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FruitsDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=200)),
                ('MRP', models.IntegerField(blank=True)),
                ('Price', models.IntegerField(blank=True)),
                ('Save', models.IntegerField(blank=True)),
                ('Big_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('First_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('Second_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('Category', multiselectfield.db.fields.MultiSelectField(choices=[('Nothing', 'Nothing'), ('Popularity', 'Popularity'), ('Best Selling', 'Best Selling')], max_length=200)),
                ('About_product', models.CharField(blank=True, max_length=500)),
                ('Storage', models.CharField(blank=True, max_length=100)),
                ('Benefits', models.CharField(blank=True, max_length=500)),
                ('Weight_policy', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VegetableDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=200)),
                ('MRP', models.IntegerField(blank=True)),
                ('Price', models.IntegerField(blank=True)),
                ('Save', models.IntegerField(blank=True)),
                ('Big_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('First_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('Second_image', models.ImageField(blank=True, upload_to='Vegetables/')),
                ('Category', multiselectfield.db.fields.MultiSelectField(choices=[('Nothing', 'Nothing'), ('Popularity', 'Popularity'), ('Best Selling', 'Best Selling')], max_length=200)),
                ('About_product', models.CharField(blank=True, max_length=500)),
                ('Storage', models.CharField(blank=True, max_length=100)),
                ('Benefits', models.CharField(blank=True, max_length=500)),
                ('Weight_policy', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
